Document: elb-tool
Title: Debian elb-tool Manual
Author: <insert document author here>
Abstract: This manual describes what elb-tool is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/elb-tool/elb-tool.sgml.gz

Format: postscript
Files: /usr/share/doc/elb-tool/elb-tool.ps.gz

Format: text
Files: /usr/share/doc/elb-tool/elb-tool.text.gz

Format: HTML
Index: /usr/share/doc/elb-tool/html/index.html
Files: /usr/share/doc/elb-tool/html/*.html
